name: Auto-commit
on:
  schedule:
    - cron: '59 23 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Git config
        run: |
          git config --global user.name "Sou Yonamine"
          git config --global user.email "sasisusesou24@gmail.com"
      - name: Commit
        run: |
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "$(date +'%Y-%m-%d')の学習" || true)
          git push

